### ISSUE TITLE
Feature request: Shuffle button

### ISSUE THREAD

**Issue by mournblade** [Alexco500/sidplay5#23]
I have a long playlist that i always play randomized. 

It would be great with a shuffle button, perhaps to the right of the other buttons, or perhaps to the right of author search.

**Comment by Alexco500** [comment]
You mean a button which shuffles the playlist, so that you can play the list from top to bottom, without using the randomized play?

**Comment by mournblade** [comment]
No not quite, I want to keep the list as-is. However - if you want to start playing your list in shuffle mode, you still have to click an item in the list to start playing. If you had a shuffle button, it would randomise a row number and then start playing that item. :)

**Comment by Alexco500** [comment]
Okay, you want a shuffle play button which does the following when clicked:
- enable shuffle mode for this play list
- randomly select one start song and start playing

And if you press the stop button, it will stop (haha) and deactivate the shuffle mode.
Because the shuffle mode is something which is also saved in the application preferences file, and it would be always active until you press the shuffle button (the one above the playlist in upper right corner) again.

Is that what you want?

**Comment by mournblade** [comment]
The way it works in streaming services (I think most?) is that you have a global shuffle setting, like in sidplay. This affects if the next song is shuffled whatever playing your context is - playlist, album etc. But it also has a play and shuffle button on the top of your context.  pressing a song in an album will play or shuffle from that point in the list depending on whether you have that setting turned on. This is the way it works in Sidplay today.

What for example Apple Music also has, is play and shuffle buttons on top of the playlist/album. When you them, it plays or shuffles the playlist/album, and it turns the global setting on and off. That shuffle button is what I was suggesting. 

I added a screenshot from Apple Music to illustrate, hope it makes sense.

![playlist_shuffle](https://github.com/Alexco500/sidplay5/assets/3775802/fd3c448f-d6cc-4729-bc81-01b9ae599be7)

**Comment by Alexco500** [comment]
Okay, so basically a shortcut for shuffle and play.
I implemented that as a toolbar item, because the items in the upper right corner change the overall way the playlist/tune is played.
BTW, I am thinking about major UI changes (something like Apple Music), so maybe later the position will change again...

**Comment by mournblade** [comment]
This is great! Tried it and it works like a charm. (I actually got the project into Xcode and started fiddling around but you beat me to it!)

Gonna listen to our old demo-songs all day :)

**Comment by Alexco500** [comment]
Great that you like it :-)

**Comment by mournblade** [comment]
Sidenote: Gave you 10/10 as a coder on CSDB :)
